TARGET_EXEC := tflite-micro-test

BUILD_DIR := build
SRC_DIRS := src

SRCS := $(shell find $(SRC_DIRS) -name '*.c')
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)
DEPS := $(OBJS:.o=.d)

INC_DIRS := $(shell find $(SRC_DIRS) -type d)
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

# -Werror
CFLAGS := -g3 -Wall -Wextra -Wpedantic $(INC_FLAGS) -MMD -MP -I../../include
LDFLAGS := -Wl,-rpath=../../bin ../../bin/libtensorflowlite_c.so -lm

CC := clang

EXECUTABLE := $(BUILD_DIR)/$(TARGET_EXEC)

test: executable
	./$(EXECUTABLE)

all: CFLAGS += -O3 -DNDEBUG
all: executable

debug: CFLAGS += -g3 -D_FORTIFY_SOURCE=2
debug: executable

san: debug
san: CFLAGS += -fsanitize=address,undefined
san: LDFLAGS += -fsanitize=address,undefined

executable: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDFLAGS)

$(BUILD_DIR)/%.c.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean compdb valgrind

clean:
	@rm -rf $(BUILD_DIR)

compdb: clean
	@bear -- $(MAKE) tflite
	@mv compile_commands.json build

valgrind: debug
	@valgrind ./$(EXECUTABLE)

-include $(DEPS)
